"use client"
import { motion, useInView } from "framer-motion"
import { useRef } from "react"
import { Target, Compass, ShieldCheck } from "lucide-react"

const ease = [0.22, 1, 0.36, 1] as const;

const cards = [
    {
        icon: Target,
        title: "Accuracy First",
        description: "Every mathematical answer is computed through symbolic execution — not generated by language model probability.",
        bullets: [
            "SymPy-powered symbolic verification",
            "Deterministic, reproducible results",
        ],
    },
    {
        icon: Compass,
        title: "Purpose Built",
        description: "Designed exclusively for actuarial science and mathematical sciences — not a general-purpose chatbot.",
        bullets: [
            "SOA & IFoA exam-aligned content",
            "Domain-specific math engine",
        ],
    },
    {
        icon: ShieldCheck,
        title: "Trust Every Answer",
        description: "Full audit trail for every computation. See the code, the execution, and the verification proof.",
        bullets: [
            "Source citations with page references",
            "Transparent verification pipeline",
        ],
    },
];

export function WhyKokademia() {
    const ref = useRef(null);
    const isInView = useInView(ref, { once: true, margin: "-100px" });

    return (
        <section ref={ref} className="py-24 lg:py-32 px-6 lg:px-8 bg-ivory-dark/30">
            <div className="max-w-7xl mx-auto">
                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: 12 }}
                    animate={isInView ? { opacity: 1, y: 0 } : {}}
                    transition={{ duration: 0.42, ease }}
                    className="text-center max-w-2xl mx-auto mb-14"
                >
                    <h2 className="text-[32px] md:text-[40px] font-bold tracking-[-0.03em] text-rich-black leading-[1.1]">
                        Why Kokademia?
                    </h2>
                    <p className="text-[17px] text-muted-text mt-4 leading-relaxed">
                        The difference between AI that guesses and AI that proves.
                    </p>
                </motion.div>

                {/* Cards */}
                <div className="grid md:grid-cols-3 gap-6">
                    {cards.map((card, i) => {
                        const Icon = card.icon;
                        return (
                            <motion.div
                                key={card.title}
                                initial={{ opacity: 0, y: 16 }}
                                animate={isInView ? { opacity: 1, y: 0 } : {}}
                                transition={{ duration: 0.42, delay: i * 0.1, ease }}
                                className="glass-card-light p-8 group"
                            >
                                <div className="w-12 h-12 rounded-2xl bg-gold/[0.1] flex items-center justify-center mb-5 group-hover:bg-gold/[0.18] transition-colors duration-300">
                                    <Icon className="w-6 h-6 text-gold" />
                                </div>

                                <h3 className="text-[20px] font-bold text-rich-black mb-2">
                                    {card.title}
                                </h3>
                                <p className="text-[14px] text-muted-text leading-relaxed mb-4">
                                    {card.description}
                                </p>

                                <ul className="space-y-2">
                                    {card.bullets.map((bullet) => (
                                        <li key={bullet} className="flex items-start gap-2 text-[13px] text-muted-text">
                                            <span className="w-1.5 h-1.5 rounded-full bg-gold mt-1.5 shrink-0" />
                                            {bullet}
                                        </li>
                                    ))}
                                </ul>
                            </motion.div>
                        );
                    })}
                </div>
            </div>
        </section>
    );
}
